name: smartedu
dependencies:
  - python=3.6
  - pip:
      - pymysql
      - pyecharts
      - pandas
      - flask
      - flask-cors
      - pylint
      - yapf
      - pymysql
      - gunicorn
      - gevent
      - aliyun-python-sdk-core
      - aliyun-python-sdk-vod
